### ISSUE TITLE
Enable Envoy access logs.

### ISSUE THREAD

**Issue by jmprusi** [3scale/kourier#17]
- [ ] Define a good enough log format 
- [ ] Output envoy access logs to stdout:

Example:
```
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
```
