### ISSUE TITLE
ClusterIngress Timeout support

### ISSUE THREAD

**Issue by jmprusi** [3scale/kourier#21]
ClusterIngress allows to set a "timeout" at the path level:

```
     http:
        paths:
        - appendHeaders:
            Knative-Serving-Namespace: knative-serving
            Knative-Serving-Revision: limited-hellogo-l24lk
          retries:
            attempts: 3
            perTryTimeout: 10m0s
          splits:
          - percent: 100
            serviceName: limited-hellogo-l24lk
            serviceNamespace: knative-serving
            servicePort: 80
          timeout: 10m0s. <-----
    visibility: ExternalIP
```
